### ISSUE TITLE
tunneling socket could not be established Error

### ISSUE THREAD

**Issue by raJSN** [forcedotcom/sfdx-simple#32]
Hello All,

I am facing below error while trying to authorize my development hub org. Please help on this.

I am following this trailhead.

![sfdx-tunneling-error](https://user-images.githubusercontent.com/3901703/33553826-46fc339c-d920-11e7-9a68-e5a2ba9a7b4a.png)

Regards,
Raj

**Comment by amphro** [comment]
It's probably because you are behind a proxy. Try setting the proxy env variables shown here: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_firewall.htm?search_text=proxy

**Comment by raJSN** [comment]
Hmm.. After setting proxy i am gettnig below error:
C:\Users\640829>sfdx force:auth:web:login
ERROR:  tunneling socket could not be established, cause=socket hang up.

Any ideas on this?

**Comment by raJSN** [comment]
![image](https://user-images.githubusercontent.com/3901703/33590745-54cab200-d9a7-11e7-8601-67fa1665baae.png)

**Comment by raJSN** [comment]
I checked it further, and my team thinks this should be local host issue, as it is hanging on this url.

http://localhost:1717/OauthRedirect?code=aPrxshT49BthlzJ4R4RpOPi......................TLWAd9lEBcy30C6FGZdlCCKo2z0HVdg.AHD1DrzJA%3D%3D&state=4748021cc03c

What should be done for this issue? reinstallation ??

**Comment by amphro** [comment]
It should be HTTPS_PROXY, not HTTPs_PROXY, but not sure if that will do anything. 

It is not a localhost issue. The flow is:
1. The command starts a server on 1717 then opens the browser
1. You login through the browser and it calls the local server at 1717
1. The server (command) gets the auth code from the request and initiates the oauth flow which fails because of the socket hangup.

So the localhost request actually is getting to the command, it just can't connect to salesforce. I'm pretty sure this is still a proxy issue. You can try to use something like wget for windows to see if you can send request to salesforce from the terminal. It might also be worth setting those proxy values globally with setx or maybe even in the env var section of setup. Otherwise, maybe research some common problems with proxies and windows command prompt.

**Comment by raJSN** [comment]
Hmm, this was indeed proxy issue. Local support fixed it.

**Comment by wdingcot** [comment]
Can you kindly provide further detail information for how this has been fixed

**Comment by udhayaganesh85** [comment]
> Hmm, this was indeed proxy issue. Local support fixed it.

I tried by giving PROXY , but no luck. I know this is somethng to do with PROXY setting.
Can you help us by providing the more information.

**Comment by abuwahid16** [comment]
I setup the PROXY in system environment variable, npm config and also the project settings file, authorization is successful, but sometimes it's failing to retrieve from source and returns "tunneling socket could not be established, statusCode=407"

**Comment by abuwahid16** [comment]
> 
> 
> Hmm, this was indeed proxy issue. Local support fixed it.

What was the fix?

**Comment by abuwahid16** [comment]
Update: my infrastructure team added my IP to SSL tunneling through the proxy, which also requires static IP. So far I don't have the authorization issue.
So even after the HTTP_PROXY and HTTPS_PROXY settings you need to make sure your IP is added to the SSL tunneling through the proxy.
