### ISSUE TITLE
Facing issue while installing sfdx on Ubuntu 17.10

### ISSUE THREAD

**Issue by raJSN** [forcedotcom/sfdx-simple#33]
I am facing attached error when installing sfdx.

![screenshot from 2017-12-16 20-32-11](https://user-images.githubusercontent.com/3901703/34071740-1c54ea1e-e2a1-11e7-881f-ab704db70ab3.png)

Any help appreciated.

**Comment by donaldrivard** [comment]
Do you have node installed?

On Dec 16, 2017 10:09 AM, "RajendraSinghNagar" <notifications@github.com>
wrote:

I am facing attached error when installing sfdx.

[image: screenshot from 2017-12-16 20-32-11]
<https://user-images.githubusercontent.com/3901703/34071740-1c54ea1e-e2a1-11e7-881f-ab704db70ab3.png>

Any help appreciated.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/forcedotcom/sfdx-simple/issues/33>, or mute the thread

**Comment by raJSN** [comment]
Well, Yes Node 9.3 was installed in my machine. 

I don't know how, but sfdx commands are working now. May be system restart worked :P.

Regards,
Raj
